export const TripsData = [
  {
   id: '1',
   name: 'Agadir/Taghazout',
   price: 6500,
   description: 'Whether you are looking for a beach holiday or an adventure in the desert, Agadir has something for everyone.',
   quantity: 8,
   image: 'https://www.visitmorocco.com/sites/default/files/thumbnails/image/AGADIR-%287%29.jpg',
   Contact: '+212657813273',
 },

 {
   id: '2',
   name: 'Tangier',
   price: 4500,
   description: 'Tangier has for centuries been Europe gateway to Africa Its blend of cultures and influences is unique in Morocco.',
   quantity: 6,
   image: 'https://www.planetware.com/wpimages/2021/07/morocco-tangier-top-attractions-discover-spains-other-enclave-melilla.jpg',
   Contact: '212687815273' ,
 },
 {
   id: '3',
   name: 'Casablanca',
   price: 2800,
   description: 'Casablanca, the economic capital of Morocco, is a bustling and vibrant city that is definitely worth a visit',
   quantity: 9,
   image: 'https://aujourdhui.ma/wp-content/uploads/2020/09/Casablanca-patrimoine.jpg?x92672',
   Contact: '+212677817273' ,
 },
 {
   id: '4',
   name: 'Marrakech',
   price: 3000,
   description: 'Marrakech is a captivating destination and there has never been a better time to visit',
   quantity: 7,
   image: 'https://www.visitmorocco.com/sites/default/files/styles/thumbnail_destination_background_top5/public/thumbnails/image/koutoubia-mosque-minaret-located-at-medina-quarter-of-marrakesh-morocco-balate-dorin.jpg?itok=08hAHERp',
   Contact: '+212687815273' ,
 },
 {
   id: '5',
   name: 'Ifrane',
   price: 1200,
   description: 'visit the beautiful city of ifrane and enjoy the snow',
   quantity: 4,
   image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/a7/9f/02/michlifen-ifrane-suites.jpg?w=500&h=300&s=1',
   Contact: '+212687865277' ,
 },
];